### ISSUE TITLE
Problem with data in Home Assistant 2021.9.7

### ISSUE THREAD

**Issue by koles142** [bieniu/ha-zadnego-ale#11] opened 2021-09-23 20:47 UTC
Hi, 
I have no data in HA (sensors are unavailable). In log I have:

https://pastebin.com/chmu0ue3

Second, before last update HA every sensors was in English instead Polish language.

Could you check this?

**Comment by bieniu** [comment] 2021-09-24 06:47
Which version of the integration? Which region? I can't reproduce this error.


> before last update HA every sensors was in English instead Polish language

Look here https://github.com/bieniu/ha-zadnego-ale/issues/9

**Comment by koles142** [comment] 2021-09-24 08:10
Version: 0.5.1
Region: Sudety

After remove integration I can’t add it again: Unknown error occurred

**Comment by bieniu** [comment] 2021-09-24 09:17
Fixed via https://github.com/bieniu/ha-zadnego-ale/commit/f40d04ac39111d85680df58263dddd23ec894d9b

**Closed by bieniu** 2021-09-24 09:17 UTC
